name: UbuntuCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    
    - name: Build P, MAVSDK, and FlightSystem
      run: build.sh
      working-directory: ${{github.workspace}}
